<?php
/*
 * TODO :
 * move the 2 CONTENT TYPES + 4 IMAGE STYLES + 1 VIEW into this module programmatically?
 */
/**
 * hook_menu
 */
function qscreensaver_api_menu() {
  $items = array(
		'xml' => array(
			'title' => 'XML API',
			'page callback' => 'qscreensaver_api_xml',
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
		)
	);
	/*
  $items['xml/example'] = array(
    'title' => 'XML API Example',
    'page callback' => 'qscreensaver_api_example',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
	*/
	return $items;
}
/**
 * callback to generate our XML grouping Slides
 * by Portrait/Landscape (content type) + Folder Name (Category taxonomy)
 */
function qscreensaver_api_xml() {
	header('Content-Type: text/xml');

  $xml = '<?xml version="1.0" encoding="UTF-8" ?>
	<rss version="2.0" xml:base="http://screensaver.deviceshowcase.com/" xmlns:atom="http://www.w3.org/2005/Atom">
		<channel>
			<title>Qualcomm Screensaver</title>
			<link>http://screensaver.deviceshowcase.com/</link>
			<atom:link rel="self" href="http://screensaver.deviceshowcase.com/xml" />
			<pubDate>Wed, 14 Nov 2013 16:43:58 -0600</pubDate>
			<lastBuildDate>Wed, 15 Nov 2013 12:24:20 -0500</lastBuildDate>';
	// load our slides & group em		
	$slides = views_get_view_result( 'slides_xml' );
	$folders = array();
	$currentmode = '';
	$currentfolder = '';
	foreach ( $slides as $s ) {
		if ( ( $s->node_type != $currentmode ) || ( $s->field_field_slide_category[0]['raw']['taxonomy_term']->name != $currentfolder ) ) {
			// new group
			$currentmode = $s->node_type;
			$currentfolder = $s->field_field_slide_category[0]['raw']['taxonomy_term']->name;
		}
		$fs = ( $currentmode == 'portrait_slide' ? 'portrait' : 'landscape' ) .'_';
		$fk = $fs . $currentfolder;
		
		$image = image_style_path( ( $currentmode == 'portrait_slide' ? 'p' : 'l' ), $s->file_managed_file_usage_uri );
		$image_info = image_get_info( $image );
		$folders[$fk][] = array(
			'source' => file_create_url( $image ),
			'filesize' => $image_info['file_size'],
		);
	}
	$xml .= '<folders count="'. count($folders) .'">';
	foreach ( $folders as $k => $v ) {
		$xml .= '
				<folder name="'. $k .'" count="'. count($v) .'" enabled="true">';
				
		foreach ( $v as $i ) {
			$xml .= '
					<item>
						<source>'. $i['source'] .'</source>
						<filesize>'. $i['filesize'] .'</filesize>
					</item>';
		}
		
		$xml .= '
				</folder>';
	}
	$xml .= '
			</folders>
		</channel>
	</rss>';
	print $xml;
	drupal_exit();
}
/**
 * creates original example XML API
 */
function qscreensaver_api_example() {
	header('Content-Type: text/xml');

  $xml = '<?xml version="1.0" encoding="UTF-8" ?>
	<rss version="2.0" xml:base="http://www.deviceshowcase.com/" xmlns:atom="http://www.w3.org/2005/Atom">
		<channel>
			<title>Qualcomm Screensaver</title>
			<link>http://screensaver.deviceshowcase.com/</link>
			<atom:link rel="self" href="http://screensaver.deviceshowcase.com/xml/example" />
			<pubDate>Wed, 14 Nov 2013 16:43:58 -0600</pubDate>
			<lastBuildDate>Wed, 15 Nov 2013 12:24:20 -0500</lastBuildDate>
			<folders count="6">
				<folder name="landscape_snapdragon" count="6" enabled="true">
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/1-Smartphone-First.jpg</source>
						<filesize>152798</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/2-Smartphone-IQ.jpg</source>
						<filesize>339946</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/3-Snapdragon-All.jpg</source>
						<filesize>213465</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/4-Snapdragon-mobile.jpg</source>
						<filesize>90909</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/5-Snapdragon-PC.jpg</source>
						<filesize>123204</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/6-is-qualcomm.jpg</source>
						<filesize>124647</filesize>
					</item>
				</folder>
				<folder name="portrait_snapdragon" count="6" enabled="true">
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/Smartphone-First-time-buyers.jpg</source>
						<filesize>195519</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/Smartphone-IQ-Smartphone-101.jpg</source>
						<filesize>489979</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/Snapdragon-All-in-one-integration.jpg</source>
						<filesize>428850</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/Snapdragon-mobile-all-day.jpg</source>
						<filesize>69896</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/Snapdragon-PC-in-your-pocket.jpg</source>
						<filesize>145994</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/who-is-qualcomm.jpg</source>
						<filesize>165465</filesize>
					</item>
				</folder>
				<folder name="landscape_brandbgs" count="4" enabled="true">
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/7-snapdragon-bg.jpg</source>
						<filesize>157546</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/8-gobi-bg.jpg</source>
						<filesize>237492</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/9-atheros-bg.jpg</source>
						<filesize>215764</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/10-qrd-bg.jpg</source>
						<filesize>134482</filesize>
					</item>
				</folder>
				<folder name="portrait_brandbgs" count="4" enabled="true">
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/snapdragon-bg.jpg</source>
						<filesize>308551</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/gobi-bg.jpg</source>
						<filesize>337737</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/atheros-bg.jpg</source>
						<filesize>305428</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/qrd-bg.jpg</source>
						<filesize>290940</filesize>
					</item>
				</folder>
				<folder name="landscape_categorybgs" count="2" enabled="false">
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/11-smartphone-bg.jpg</source>
						<filesize>163116</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/l/12-computing-bg.jpg</source>
						<filesize>173810</filesize>
					</item>
				</folder>
				<folder name="portrait_categorybgs" count="2" enabled="false">
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/smartphone-bg.jpg</source>
						<filesize>179685</filesize>
					</item>
					<item>
						<source>http://screensaver.deviceshowcase.com/sites/all/modules/custom/qscreensaver_api/images/p/computing-bg.jpg</source>
						<filesize>246682</filesize>
					</item>
				</folder>
			</folders>
		</channel>
	</rss>';
	print $xml;
	drupal_exit();
}